### ISSUE TITLE
Program changes on the same tick often play previous instrument.

### ISSUE THREAD

**Issue by easyaspi314** [abreheret/MidiEditor#4]
Again, this is mostly an issue with low-res MIDIs. 

Occasionally, depending on the file, if you have a Program Change event on the same tick that a note starts on, the previous instrument will play. So, if I change from String Ensemble 1 to Acoustic Grand Piano on tick 48 and have a note that also starts on tick 48, the note tends to play in strings instead of piano.

This also happens on the beginning of the song. If I continued said example, and played it to a tick after 48, then played the song from the beginning, the first note would often play in piano instead of strings. However, stopping playback before a second program change seems to be a workaround.

I notice that program changes, control changes, labels, etc., are always put a tick early:  
If I enable snapping and right click to put my program change event at tick 96, as soon as I let go, the event will move to tick 95. This can be mildly annoying, especially when manually adding volume changes.

**Comment by abreheret** [comment]
Can you test my release 3.1.2  ? Available in windows 32 and 64 here : 
https://github.com/abreheret/MidiEditor/releases
